import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
// import Header from "@/_components/layouts/header";
import AuthProvider from "@/_components/common/auth-provider";
import ThemeRegistry from "@/_components/themeRegistry/theme-registry";
//import Footer from "@/_components/layouts/footer";
// import { Inter } from "next/font/google";
// const inter = Inter({ subsets: ["latin"] });
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "NgTech",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        // className={inter.className}
      >
        {/* <Header /> */}
        {/* Auth Middleware */}
        <AuthProvider>
          <ThemeRegistry>{children}</ThemeRegistry>
        </AuthProvider>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
